-- PSQL-ONLY / DISPOSABLE DATABASE ONLY. Never run against a linked database.
\set ON_ERROR_STOP on
\ir fixtures/libri_images_private_storage_base.sql
\ir ../../scripts/database/provision-libri-worker-role.sql
GRANT USAGE ON SCHEMA libri TO libri_worker;
\ir ../migrations/20260906184227_libri_private_image_upload_admission.sql

CREATE TABLE public.buildos_upload_lease_control (id integer PRIMARY KEY, value text);
INSERT INTO public.buildos_upload_lease_control VALUES (1, 'unchanged');
CREATE TEMP TABLE policies_before AS SELECT * FROM pg_policies WHERE schemaname <> 'libri';
CREATE TEMP TABLE buckets_before AS SELECT * FROM storage.buckets;
CREATE TEMP TABLE shared_columns_before AS SELECT table_schema, table_name, column_name, data_type
	FROM information_schema.columns WHERE table_schema IN ('public', 'auth', 'storage');
\ir ../migrations/20260906201700_libri_upload_processing_leases.sql

CREATE FUNCTION pg_temp.assert_true(ok boolean, message text) RETURNS void LANGUAGE plpgsql AS $$
BEGIN
	IF ok IS DISTINCT FROM true THEN RAISE EXCEPTION 'assertion failed: %', message; END IF;
END;
$$;
CREATE FUNCTION pg_temp.expect_error(statement text, expected text) RETURNS void LANGUAGE plpgsql AS $$
BEGIN
	BEGIN EXECUTE statement;
	EXCEPTION WHEN OTHERS THEN
		IF SQLSTATE = expected THEN RETURN; END IF;
		RAISE EXCEPTION 'expected SQLSTATE %, got %: %', expected, SQLSTATE, SQLERRM;
	END;
	RAISE EXCEPTION 'expected SQLSTATE %, statement succeeded', expected;
END;
$$;

SELECT pg_temp.assert_true(NOT EXISTS (SELECT 1 FROM libri.image_upload_controls)
	AND NOT EXISTS (SELECT 1 FROM libri.image_upload_processing), 'migration is empty/default-off');
SELECT pg_temp.assert_true((SELECT relrowsecurity AND relforcerowsecurity FROM pg_class
	WHERE oid = 'libri.image_upload_processing'::regclass), 'processing forces RLS');
SELECT pg_temp.assert_true(NOT EXISTS (
	SELECT 1 FROM unnest(ARRAY['anon','authenticated','libri_worker']) AS role_name
	WHERE has_table_privilege(role_name, 'libri.image_upload_processing', 'SELECT, INSERT, UPDATE, DELETE')
), 'no client or worker raw lease access');
SELECT pg_temp.assert_true(NOT has_table_privilege('libri_worker','libri.image_upload_intents','SELECT,INSERT,UPDATE,DELETE')
	AND NOT has_table_privilege('libri_worker','libri.image_upload_controls','SELECT,INSERT,UPDATE,DELETE'),
	'worker gains no raw admission access');
SELECT pg_temp.assert_true(NOT EXISTS (
	SELECT 1 FROM pg_proc WHERE oid IN (
		'libri.list_image_upload_candidates(uuid)'::regprocedure,
		'libri.claim_image_upload(uuid,uuid,uuid)'::regprocedure,
		'libri.fail_image_upload(uuid,uuid,uuid,integer,text)'::regprocedure)
	AND (NOT prosecdef OR NOT proconfig @> ARRAY['search_path=pg_catalog, libri']
		OR NOT has_function_privilege('libri_worker', oid, 'EXECUTE')
		OR has_function_privilege('anon', oid, 'EXECUTE')
		OR has_function_privilege('authenticated', oid, 'EXECUTE')
		OR has_function_privilege('service_role', oid, 'EXECUTE'))
), 'only the isolated machine role can call lease transitions');

INSERT INTO auth.users(id) VALUES ('11111111-1111-4111-8111-111111111111'), ('22222222-2222-4222-8222-222222222222');
INSERT INTO libri.libraries(id,slug,name,created_by) VALUES
	('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1','one','One','11111111-1111-4111-8111-111111111111'),
	('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2','two','Two','22222222-2222-4222-8222-222222222222');
INSERT INTO libri.library_members(library_id,user_id,role) VALUES
	('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1','11111111-1111-4111-8111-111111111111','owner'),
	('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2','22222222-2222-4222-8222-222222222222','owner');
INSERT INTO libri.books(id,library_id,title) VALUES
	('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb1','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1','One'),
	('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb2','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2','Two');
INSERT INTO libri.image_upload_controls(library_id,admission_enabled) SELECT id,true FROM libri.libraries;
SELECT pg_temp.assert_true(NOT EXISTS (SELECT 1 FROM libri.image_upload_controls WHERE processing_enabled), 'admission alone does not activate processing');

-- Stable fixture IDs aid real-session race assertions; production IDs are generated by reserve.
INSERT INTO libri.image_upload_intents(id,library_id,book_id,requested_by,idempotency_key,file_metadata,
	object_path,created_at,signing_deadline,expires_at,status,submitted_at)
SELECT ('dddddddd-dddd-4ddd-8ddd-ddddddddddd' || n)::uuid,
	'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb1',
	'11111111-1111-4111-8111-111111111111','lease_fixture___' || n,
	'{"filename":"page.png","mimeType":"image/png","byteSize":1024,"sha256":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","imageType":"page"}',
	'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1/uploads/dddddddd-dddd-4ddd-8ddd-ddddddddddd' || n || '/original.png',
	now(),now()+interval '10 minutes',now()+interval '135 minutes','awaiting_verification',now()
FROM generate_series(1,3) n;

CREATE FUNCTION pg_temp.claim(n integer, token integer DEFAULT 1) RETURNS jsonb LANGUAGE sql AS $$
	SELECT libri.claim_image_upload('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',
		('dddddddd-dddd-4ddd-8ddd-ddddddddddd'||n)::uuid,
		('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeee'||token)::uuid)
$$;
CREATE FUNCTION pg_temp.fail_upload(n integer, token integer, attempt integer, code text) RETURNS boolean LANGUAGE sql AS $$
	SELECT libri.fail_image_upload('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',
		('dddddddd-dddd-4ddd-8ddd-ddddddddddd'||n)::uuid,
		('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeee'||token)::uuid, attempt, code)
$$;

SET ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',false);
SELECT pg_temp.expect_error('SELECT pg_temp.claim(1)', '42501');
SELECT pg_temp.expect_error('SELECT * FROM libri.image_upload_processing', '42501');
SELECT pg_temp.assert_true((SELECT count(*) = 3 FROM libri.image_upload_intents), 'requester status reads still work');
RESET ROLE;
SET ROLE libri_worker;
SELECT pg_temp.assert_true(pg_temp.claim(1) IS NULL AND NOT EXISTS (
	SELECT 1 FROM libri.list_image_upload_candidates('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1')), 'disabled gate blocks discovery and claims');
SELECT pg_temp.expect_error('UPDATE libri.image_upload_controls SET processing_enabled=true', '42501');
SELECT pg_temp.expect_error('DELETE FROM libri.image_upload_processing', '42501');
SELECT pg_temp.expect_error('SELECT libri.claim_image_upload(NULL,NULL,NULL)', '22023');
RESET ROLE;
UPDATE libri.image_upload_controls SET processing_enabled=true;
SET ROLE libri_worker;
SELECT pg_temp.assert_true((SELECT count(*) = 3 FROM libri.list_image_upload_candidates('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1')), 'submitted work is discoverable');
SELECT pg_temp.assert_true(NOT EXISTS (SELECT 1 FROM libri.list_image_upload_candidates('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2')), 'other library has no candidates');
SELECT pg_temp.assert_true(libri.claim_image_upload('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2',
	'dddddddd-dddd-4ddd-8ddd-ddddddddddd1','eeeeeeee-eeee-4eee-8eee-eeeeeeeeeee1') IS NULL, 'cross-library claim is denied');
SELECT pg_temp.assert_true((pg_temp.claim(1)->>'attempt')::integer = 1, 'first claim is attempt one');
CREATE TEMP TABLE first_claim AS SELECT pg_temp.claim(1) AS receipt;
SELECT pg_temp.assert_true(pg_temp.claim(1) = (SELECT receipt FROM first_claim), 'same-token replay is stable');
SELECT pg_temp.assert_true(pg_temp.claim(1,2) IS NULL AND pg_temp.claim(2,2) IS NULL, 'one live lease per library');
RESET ROLE;
INSERT INTO libri.image_upload_intents(id,library_id,book_id,requested_by,idempotency_key,file_metadata,
	object_path,created_at,signing_deadline,expires_at,status,submitted_at)
SELECT 'dddddddd-dddd-4ddd-8ddd-ddddddddddd4', 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2',
	'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb2','22222222-2222-4222-8222-222222222222','other_library___',file_metadata,
	'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2/uploads/dddddddd-dddd-4ddd-8ddd-ddddddddddd4/original.png',
	created_at,signing_deadline,expires_at,status,submitted_at FROM libri.image_upload_intents
	WHERE id='dddddddd-dddd-4ddd-8ddd-ddddddddddd1';
SET ROLE libri_worker;
SELECT pg_temp.assert_true((libri.claim_image_upload('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2',
	'dddddddd-dddd-4ddd-8ddd-ddddddddddd4','eeeeeeee-eeee-4eee-8eee-eeeeeeeeeee1')->>'attempt')::integer=1,
	'different library can progress while the first library has an active lease');
SELECT pg_temp.assert_true(NOT libri.fail_image_upload('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',
	'dddddddd-dddd-4ddd-8ddd-ddddddddddd4','eeeeeeee-eeee-4eee-8eee-eeeeeeeeeee1',1,'invalid_image'),
	'failure cannot cross library boundaries even when tokens match');
RESET ROLE;
DELETE FROM libri.image_upload_processing WHERE upload_id='dddddddd-dddd-4ddd-8ddd-ddddddddddd4';
DELETE FROM libri.image_upload_intents WHERE id='dddddddd-dddd-4ddd-8ddd-ddddddddddd4';
SET ROLE libri_worker;
SELECT pg_temp.assert_true(NOT pg_temp.fail_upload(1,2,1,'invalid_image')
	AND NOT pg_temp.fail_upload(1,1,2,'invalid_image'), 'wrong token/generation is fenced');
SELECT pg_temp.expect_error($q$SELECT pg_temp.fail_upload(1,1,1,'provider-secret')$q$, '22023');
SELECT pg_temp.assert_true(pg_temp.fail_upload(1,1,1,'storage_unavailable'), 'transient failure schedules retry');
SELECT pg_temp.assert_true(pg_temp.fail_upload(1,1,1,'storage_unavailable')
	AND NOT pg_temp.fail_upload(1,1,1,'invalid_image'), 'failure replay is idempotent only for the same outcome');
SELECT pg_temp.assert_true(pg_temp.claim(1,2) IS NULL, 'retry delay is enforced');
RESET ROLE;
UPDATE libri.image_upload_processing SET available_at=now()-interval '1 second';
SET ROLE libri_worker;
SELECT pg_temp.assert_true(pg_temp.claim(1,1) IS NULL, 'old token cannot restart the same completed attempt');
SELECT pg_temp.assert_true((pg_temp.claim(1,2)->>'attempt')::integer=2, 'fresh token starts second attempt');
SELECT pg_temp.assert_true(NOT pg_temp.fail_upload(1,1,1,'invalid_image'), 'old result cannot settle replacement lease');
RESET ROLE;
UPDATE libri.image_upload_processing SET lease_expires_at=now()-interval '1 second';
SET ROLE libri_worker;
SELECT pg_temp.assert_true(NOT pg_temp.fail_upload(1,2,2,'invalid_image'), 'expired worker cannot settle');
SELECT pg_temp.assert_true((pg_temp.claim(1,3)->>'attempt')::integer=3, 'crashed lease is reclaimable');
RESET ROLE;
UPDATE libri.image_upload_processing SET lease_expires_at=now()-interval '1 second';
SET ROLE libri_worker;
SELECT pg_temp.assert_true(pg_temp.claim(1,4) IS NULL, 'three crashed attempts cannot create a fourth');
SELECT pg_temp.assert_true((pg_temp.claim(2,1)->>'attempt')::integer=1, 'other pending upload proceeds');
RESET ROLE;
SELECT pg_temp.assert_true((SELECT status='blocked' AND last_failure='attempts_exhausted' FROM libri.image_upload_processing
	WHERE upload_id='dddddddd-dddd-4ddd-8ddd-ddddddddddd1'), 'exhausted work is durably blocked');
UPDATE libri.image_upload_controls SET processing_enabled=false;
UPDATE libri.library_members SET role='viewer' WHERE library_id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1';
SET ROLE libri_worker;
SELECT pg_temp.assert_true(pg_temp.claim(2,1) IS NULL, 'disable/revocation prevents even same-token receipt replay');
SELECT pg_temp.assert_true(pg_temp.fail_upload(2,1,1,'cancelled'), 'failure-only release works after disable/revocation');
RESET ROLE;
UPDATE libri.image_upload_controls SET processing_enabled=true;
SET ROLE libri_worker;
SELECT pg_temp.assert_true(pg_temp.claim(3) IS NULL, 'viewer cannot originate processing');
RESET ROLE;
UPDATE libri.library_members SET role='owner' WHERE library_id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1';
UPDATE libri.image_upload_intents SET status='reserved',submitted_at=NULL WHERE id='dddddddd-dddd-4ddd-8ddd-ddddddddddd3';
SET ROLE libri_worker;
SELECT pg_temp.assert_true(pg_temp.claim(3) IS NULL, 'reservation alone is not an enqueue');
RESET ROLE;
UPDATE libri.image_upload_intents SET status='awaiting_verification',submitted_at=now(),
	created_at=now()-interval '134 minutes 50 seconds',signing_deadline=now()-interval '124 minutes 50 seconds',
	expires_at=now()+interval '10 seconds' WHERE id='dddddddd-dddd-4ddd-8ddd-ddddddddddd3';
SET ROLE libri_worker;
SELECT pg_temp.assert_true((pg_temp.claim(3)->>'lease_expires_at')::timestamptz <= now()+interval '10 seconds', 'lease never outlives upload reservation');
RESET ROLE;
UPDATE libri.image_upload_intents SET created_at=now()-interval '136 minutes',
	signing_deadline=now()-interval '126 minutes',expires_at=now()-interval '1 minute'
	WHERE id='dddddddd-dddd-4ddd-8ddd-ddddddddddd3';
SET ROLE libri_worker;
SELECT pg_temp.assert_true(pg_temp.claim(3) IS NULL AND NOT pg_temp.fail_upload(3,1,1,'invalid_image'), 'expired reservation cannot resume or accept late results');
RESET ROLE;
SELECT pg_temp.assert_true((SELECT count(*)=3 FROM libri.image_upload_intents WHERE status='awaiting_verification'),
	'failure/exhaustion never releases pending capacity');
SELECT pg_temp.expect_error($q$DELETE FROM libri.image_upload_intents WHERE id='dddddddd-dddd-4ddd-8ddd-ddddddddddd1'$q$, '23503');
SELECT pg_temp.assert_true(NOT EXISTS (SELECT 1 FROM libri.images) AND NOT EXISTS (SELECT 1 FROM libri.sources)
	AND NOT EXISTS (SELECT 1 FROM storage.objects), 'leases do not publish images, sources or bytes');
SELECT pg_temp.assert_true((SELECT value='unchanged' FROM public.buildos_upload_lease_control WHERE id=1)
	AND NOT EXISTS ((SELECT * FROM pg_policies WHERE schemaname <> 'libri' EXCEPT SELECT * FROM policies_before)
		UNION ALL (SELECT * FROM policies_before EXCEPT SELECT * FROM pg_policies WHERE schemaname <> 'libri'))
	AND NOT EXISTS ((SELECT * FROM storage.buckets EXCEPT SELECT * FROM buckets_before)
		UNION ALL (SELECT * FROM buckets_before EXCEPT SELECT * FROM storage.buckets))
	AND NOT EXISTS ((SELECT table_schema,table_name,column_name,data_type FROM information_schema.columns
		WHERE table_schema IN ('public','auth','storage') EXCEPT SELECT * FROM shared_columns_before)
		UNION ALL (SELECT * FROM shared_columns_before EXCEPT SELECT table_schema,table_name,column_name,data_type
		FROM information_schema.columns WHERE table_schema IN ('public','auth','storage'))), 'shared application structure/data/policies unchanged');

-- Reset only this disposable fixture for the observed overlapping-session runner.
DELETE FROM libri.image_upload_processing;
UPDATE libri.image_upload_intents SET created_at=now(),signing_deadline=now()+interval '10 minutes',expires_at=now()+interval '135 minutes';
SELECT 'upload processing lease contract passed' AS result;
