[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-9_x"]

[phases.install]
dependsOn = ["setup"]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
dependsOn = ["install"]
cmds = ["pnpm turbo build --filter=@buildos/worker"]

[start]
cmd = "node apps/worker/dist/index.js"