// apps/worker/scripts/build-emoji-catalog.ts
//
// Builds the project emoji catalog out of Unicode's emoji-test.txt, into two identical files:
// the one Jev picks from (worker) and the one the web emoji picker browses (web). Two copies
// keep both apps free of a shared-package build step.
//
// Kept: fully-qualified emoji up to MAX_EMOJI_VERSION, so they render on older phones and
// Windows. Dropped: the Component group (skin tones, hair), skin-tone variants, and gendered
// duplicates (the neutral person stays: 🧑‍💻 yes, 👩‍💻 and 👨‍💻 no).
//
//   pnpm exec tsx scripts/build-emoji-catalog.ts [--source emoji-test.txt]

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const UNICODE_VERSION = '16.0';
const SOURCE_URL = `https://unicode.org/Public/emoji/${UNICODE_VERSION}/emoji-test.txt`;
const MAX_EMOJI_VERSION = 15.0;
const REPO = (() => {
	let dir = process.cwd();
	while (!existsSync(join(dir, 'pnpm-workspace.yaml')) && dirname(dir) !== dir)
		dir = dirname(dir);
	return dir;
})();
const OUTS = [
	'apps/worker/src/workers/project-emoji/emoji-catalog.generated.ts',
	'apps/web/src/lib/components/project/emoji/emoji-catalog.generated.ts'
];

const SKIN_TONES = [0x1f3fb, 0x1f3fc, 0x1f3fd, 0x1f3fe, 0x1f3ff];
const GENDER_SIGNS = [0x2640, 0x2642];
const MAN_WOMAN = [0x1f468, 0x1f469];
const ZWJ = 0x200d;

type Row = {
	cps: number[];
	glyph: string;
	version: number;
	name: string;
	group: string;
	subgroup: string;
};

function parse(text: string): Row[] {
	const rows: Row[] = [];
	let group = '';
	let subgroup = '';
	for (const raw of text.split('\n')) {
		const line = raw.trim();
		if (line.startsWith('# group:')) group = line.slice(8).trim();
		else if (line.startsWith('# subgroup:')) subgroup = line.slice(11).trim();
		if (!line || line.startsWith('#')) continue;
		// "1F4B0 ; fully-qualified # 💰 E2.0 money bag"
		const match = /^([0-9A-F ]+?)\s*;\s*(\S+)\s*#\s*(\S+)\s+E(\d+\.\d+)\s+(.+)$/.exec(line);
		if (!match || match[2] !== 'fully-qualified') continue;
		rows.push({
			cps: match[1]!.split(' ').map((hex) => parseInt(hex, 16)),
			glyph: match[3]!,
			version: Number(match[4]),
			name: match[5]!.trim(),
			group,
			subgroup
		});
	}
	return rows;
}

function keep(row: Row): boolean {
	if (row.group === 'Component' || row.version > MAX_EMOJI_VERSION) return false;
	if (row.cps.some((cp) => SKIN_TONES.includes(cp) || GENDER_SIGNS.includes(cp))) return false;
	return !(row.cps.includes(ZWJ) && row.cps.some((cp) => MAN_WOMAN.includes(cp)));
}

async function main() {
	const sourceArg = process.argv.indexOf('--source');
	const text =
		sourceArg > 0
			? readFileSync(process.argv[sourceArg + 1]!, 'utf8')
			: await (await fetch(SOURCE_URL)).text();
	const rows = parse(text).filter(keep);
	const quote = (value: string) => `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
	const lines = rows.map(
		(row) => `\t[${[row.glyph, row.name, row.group, row.subgroup].map(quote).join(', ')}],`
	);
	for (const out of OUTS) {
		writeFileSync(
			join(REPO, out),
			[
				`// ${out}`,
				`// GENERATED by scripts/build-emoji-catalog.ts from Unicode emoji-test.txt ${UNICODE_VERSION}`,
				`// (emoji ≤ ${MAX_EMOJI_VERSION.toFixed(1)}, no skin-tone or gendered variants). Do not edit by hand.`,
				'',
				'/** [glyph, Unicode name, group, subgroup] */',
				'export type EmojiCatalogRow = readonly [',
				'\tglyph: string,',
				'\tname: string,',
				'\tgroup: string,',
				'\tsubgroup: string',
				'];',
				'',
				'export const EMOJI_CATALOG: readonly EmojiCatalogRow[] = [',
				...lines.map((line, index) =>
					index === lines.length - 1 ? line.slice(0, -1) : line
				),
				'];',
				''
			].join('\n')
		);
	}
	console.log(`Wrote ${rows.length} emoji to ${OUTS.join(' and ')}`);
}

void main();
