export const CURRENT_TERMS_VERSION = '2026-07-16';
export const CURRENT_PRIVACY_VERSION = '2026-07-16';

export const CURRENT_POLICY_VERSIONS = Object.freeze({
	terms: CURRENT_TERMS_VERSION,
	privacy: CURRENT_PRIVACY_VERSION
});
