// packages/agentic-chat-runtime/src/provenance.ts
// Node-only entrypoint. Never export this from the browser/runtime barrel.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { lstatSync, readFileSync, readlinkSync } from 'node:fs';
import { resolve } from 'node:path';

export interface SourceProvenance {
	version: 1;
	gitSha: string;
	dirtyTreeSha256: string;
}

// Reports, fixtures generated by runs, and prose do not change executable code.
// Git's ignore rules exclude secrets, node_modules, dist, .svelte-kit and output.
const SOURCE_PATHS = [
	'apps',
	'packages',
	'scripts',
	'patches',
	'supabase',
	'.github',
	'package.json',
	'pnpm-lock.yaml',
	'pnpm-workspace.yaml',
	'turbo.json',
	'vitest.workers.ts',
	'vitest.coverage.ts',
	'railway.chat.toml'
];

export function readSourceProvenance(cwd = process.cwd()): SourceProvenance {
	const git = (...args: string[]) =>
		execFileSync('git', args, {
			cwd,
			encoding: 'utf8',
			stdio: ['ignore', 'pipe', 'pipe'],
			maxBuffer: 32 * 1024 * 1024
		});
	const root = git('rev-parse', '--show-toplevel').trim();
	const gitSha = git('rev-parse', 'HEAD').trim();
	// Compare the worktree to HEAD (includes staged edits), then add nonignored
	// untracked files. Hash paths, modes and actual bytes, not just dirty status.
	const changed = new Set(
		[
			...git('-C', root, 'diff', '--name-only', '-z', 'HEAD', '--', ...SOURCE_PATHS).split(
				'\0'
			),
			...git(
				'-C',
				root,
				'ls-files',
				'--others',
				'--exclude-standard',
				'-z',
				'--',
				...SOURCE_PATHS
			).split('\0')
		].filter(Boolean)
	);
	const hash = createHash('sha256');
	for (const path of [...changed].sort()) {
		hash.update(JSON.stringify(path));
		const absolute = resolve(root, path);
		try {
			const stat = lstatSync(absolute);
			hash.update(`:${stat.mode}:`);
			const bytes = stat.isSymbolicLink()
				? Buffer.from(readlinkSync(absolute))
				: readFileSync(absolute);
			hash.update(`${bytes.length}:`);
			hash.update(bytes);
		} catch (error) {
			if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
			hash.update(':deleted');
		}
		hash.update('\0');
	}
	return { version: 1, gitSha, dirtyTreeSha256: hash.digest('hex') };
}

export function assertSourceProvenance(
	expected: SourceProvenance,
	actual: unknown,
	label: string
): asserts actual is SourceProvenance {
	const observed = actual as Partial<SourceProvenance> | null;
	if (
		!observed ||
		observed.version !== 1 ||
		!/^[a-f0-9]{40}$/.test(observed.gitSha ?? '') ||
		!/^[a-f0-9]{64}$/.test(observed.dirtyTreeSha256 ?? '') ||
		observed.gitSha !== expected.gitSha ||
		observed.dirtyTreeSha256 !== expected.dirtyTreeSha256
	) {
		throw new Error(
			`${label} source provenance mismatch: expected ${JSON.stringify(expected)}, received ${JSON.stringify(actual ?? null)}. Restart both services from the same tree.`
		);
	}
}
