// apps/web/src/lib/services/agentic-chat-v2/context-models.ts
// Shared implementation for web admission and worker context preparation.
export {
	type DocMetaSummary,
	type DocStructureNodeSummary,
	type DocStructureSummary,
	type LightProject,
	type LightGoal,
	type LightMilestone,
	type LightPlan,
	type LightTask,
	type LightDocument,
	type ProjectStartHereDocument,
	type LightEvent,
	type FastChatEventWindow,
	type FastChatWorkSignal,
	type FastChatRecentChange,
	type FastChatProjectSignalSummary,
	type FastChatProjectIntelligence,
	type EntityScopeMeta,
	type DocumentScopeMeta,
	type ProjectContextMeta,
	type LightProjectMember,
	type ProjectTaskRollup,
	type GlobalContextProjectBundle,
	type GlobalProjectIndexEntry,
	type LinkedEdge,
	type GlobalContextData,
	type ProjectContextData,
	type EntityContextData,
	type DailyBriefMentionedEntity,
	type DailyBriefProjectBrief,
	type DailyBriefContextData,
	collectDocStructureIds,
	buildDocStructureSummary
} from '@buildos/agentic-chat-runtime/context';
