// apps/web/src/routes/api/admin/chat/sessions/[id]/turn-run-columns.ts

/** Columns the admin session detail loads for each turn run. */
export const TURN_RUN_COLUMNS = `
          id,
          stream_run_id,
          client_turn_id,
          source,
          context_type,
          entity_id,
          project_id,
          gateway_enabled,
          request_message,
          user_message_id,
          assistant_message_id,
          status,
          finished_reason,
          failure_code,
          tool_round_count,
          tool_call_count,
          validation_failure_count,
          llm_pass_count,
          first_lane,
          first_help_path,
          first_skill_path,
          first_canonical_op,
          history_strategy,
          history_compressed,
          raw_history_count,
          history_for_model_count,
          cache_source,
          cache_age_seconds,
          request_prewarmed_context,
          prompt_snapshot_id,
          timing_metric_id,
          started_at,
          finished_at,
          created_at,
          updated_at
        `;
