// apps/web/src/lib/tests/agentic-e2e/harness/types.ts
//
// Shared types for the agentic-chat end-to-end stress harness.
import type { ChatToolCall, LastTurnContext } from '@buildos/shared-types';
import type { TypedSupabaseClient } from '@buildos/supabase-client';

/** A chat context mode accepted by POST /api/agent/v2/stream. */
export type HarnessContextType = 'global' | 'project' | 'project_create' | 'daily_brief';

/** Everything captured from driving a single chat turn over SSE. */
export interface TurnResult {
	/** Session id assigned by the server (from the `session` event). */
	sessionId: string | null;
	/** stream_run_id echoed on every event envelope — key for telemetry joins. */
	streamRunId: string | null;
	/** client_turn_id generated by the caller and echoed by the stream. */
	clientTurnId: string;
	/** Latest continuity context emitted by the server for a follow-up turn. */
	lastTurnContext: LastTurnContext | null;
	/** Full accumulated assistant text (from `text` + `text_delta` events). */
	assistantText: string;
	/** Every tool the model asked to call this turn. */
	toolCalls: ChatToolCall[];
	/** Raw `tool_result` payloads in order. */
	toolResults: Array<Record<string, unknown>>;
	/** Skill load/request activity (`skill_activity` events). */
	skillActivity: Array<Record<string, unknown>>;
	/** Any `error` event payloads seen on the stream. */
	errors: Array<{ error: string; turn_rejected?: boolean }>;
	/** finished_reason from the terminal `done` event. */
	finishedReason: string | null;
	/** usage from the terminal `done` event, if present. */
	usage: Record<string, unknown> | null;
	/** True once a terminal `done` event was observed. */
	completed: boolean;
	/** Every parsed SSE event (envelope + payload), in order, for debugging. */
	rawEvents: Array<Record<string, unknown>>;
}

/** Result of seeding a scenario's fixtures. */
export interface SeedResult {
	/** The seeded project id (undefined for global/project_create scenarios). */
	projectId?: string;
	/** temp_id -> real entity id map returned by fixture builders. */
	entityIds: Record<string, string>;
	/** Freeform notes a scenario can stash for its assertions. */
	notes: Record<string, unknown>;
}

/** Read-only DB access handed to assertions (service-role, bypasses RLS). */
export interface DbView {
	admin: TypedSupabaseClient;
	userId: string;
	actorId: string;
}

/** The shared context every scenario hook receives. */
export interface ScenarioContext {
	baseUrl: string;
	cookie: string;
	db: DbView;
}

export interface JudgeResult {
	score: number; // 1-5
	passed: boolean;
	reasoning: string;
}

export interface JudgeSpec {
	/** What "good" looks like; rendered into the judge system prompt. */
	rubric: string;
	/** Minimum score (1-5) to pass. Default 3. */
	threshold?: number;
}

/** One turn in a (possibly multi-turn) scenario. */
export interface TurnSpec {
	message: string;
	contextType: HarnessContextType;
	/** Resolve the project/entity id to scope this turn to, from the seed result. */
	entityIdFromSeed?: (seed: SeedResult) => string | undefined;
	/** Deterministic assertions over the turn + DB + seed. Throw to fail. */
	assert: (turn: TurnResult, ctx: ScenarioContext, seed: SeedResult) => Promise<void> | void;
	/** Optional fuzzy-quality judge for this turn. */
	judge?: (
		turn: TurnResult,
		ctx: ScenarioContext,
		seed: SeedResult
	) => Promise<JudgeSpec & { transcript: string }>;
}

export interface Scenario {
	id: string;
	title: string;
	category: 'document' | 'task' | 'organization' | 'calendar' | 'email';
	/** Return true to skip (e.g. calendar without a connected test calendar). */
	skip?: () => boolean;
	/** Create fixtures. Omit for global/project_create scenarios. */
	seed?: (ctx: ScenarioContext) => Promise<SeedResult>;
	/** Turns run sequentially, reusing the session id across turns. */
	turns: TurnSpec[];
}
