// apps/web/src/lib/tests/agentic-e2e/harness/types.ts
//
// Shared types for the agentic-chat end-to-end stress harness.
import type { AgentTimingSummary, ChatToolCall, LastTurnContext } from '@buildos/shared-types';
import type { TypedSupabaseClient } from '@buildos/supabase-client';

/** A chat context mode accepted by the agentic chat turn contract. */
export type HarnessContextType = 'global' | 'project' | 'project_create' | 'daily_brief';

/** Value of `chat_turn_runs.execution_mode`. The harness only drives `worker_realtime`. */
export type AgenticE2EExecutionMode = 'legacy_sse' | 'worker_realtime';

/** Client-observed stream timing; durations are relative to the fetch start. */
export interface TurnTiming {
	requestStartedAt: string;
	responseHeadersMs: number | null;
	firstSseEventMs: number | null;
	ttftMs: number | null;
	terminalEventMs: number | null;
	totalDurationMs: number | null;
}

/** Client-observed arrival time for one SSE event, without retaining its payload. */
export interface TurnEventTiming {
	type: string;
	phase: string | null;
	sequenceIndex: number | null;
	observedMs: number;
}

/** Everything captured from driving a single chat turn over SSE. */
export interface TurnResult {
	/** Session id assigned by the server (from the `session` event). */
	sessionId: string | null;
	/** stream_run_id echoed on every event envelope — key for telemetry joins. */
	streamRunId: string | null;
	/** client_turn_id generated by the caller and echoed by the stream. */
	clientTurnId: string;
	/** Latest continuity context emitted by the server for a follow-up turn. */
	lastTurnContext: LastTurnContext | null;
	/** Full accumulated assistant text (from `text` + `text_delta` events). */
	assistantText: string;
	/** Every tool the model asked to call this turn. */
	toolCalls: ChatToolCall[];
	/** Raw `tool_result` payloads in order. */
	toolResults: Array<Record<string, unknown>>;
	/** Skill load/request activity (`skill_activity` events). */
	skillActivity: Array<Record<string, unknown>>;
	/** Any `error` event payloads seen on the stream. */
	errors: Array<{ error: string; turn_rejected?: boolean }>;
	/** finished_reason from the terminal `done` event. */
	finishedReason: string | null;
	/** usage from the terminal `done` event, if present. */
	usage: Record<string, unknown> | null;
	/** True once a terminal `done` event was observed. */
	completed: boolean;
	/** Every parsed SSE event (envelope + payload), in order, for debugging. */
	rawEvents: Array<Record<string, unknown>>;
	/** Client-side timings, including TTFT at the first SSE text/text_delta event. */
	timing: TurnTiming;
	/** Server-measured phase timings emitted immediately before the terminal done event. */
	serverTiming: AgentTimingSummary | null;
	/** Payload-free client arrival timeline used for tool-stage and finalization evidence. */
	eventTimings: TurnEventTiming[];
}

/** Result of seeding a scenario's fixtures. */
export interface SeedResult {
	/** The seeded project id (undefined for global/project_create scenarios). */
	projectId?: string;
	/** temp_id -> real entity id map returned by fixture builders. */
	entityIds: Record<string, string>;
	/** Freeform notes a scenario can stash for its assertions. */
	notes: Record<string, unknown>;
}

/** Read-only DB access handed to assertions (service-role, bypasses RLS). */
export interface DbView {
	admin: TypedSupabaseClient;
	userId: string;
	actorId: string;
}

/** The shared context every scenario hook receives. */
export interface ScenarioContext {
	baseUrl: string;
	cookie: string;
	db: DbView;
	executionMode: AgenticE2EExecutionMode;
}

export interface JudgeResult {
	score: number; // 1-5
	passed: boolean;
	reasoning: string;
}

export interface JudgeSpec {
	/** What "good" looks like; rendered into the judge system prompt. */
	rubric: string;
	/** Minimum score (1-5) to pass. Default 3. */
	threshold?: number;
}

/**
 * A quality invariant that should be measured without aborting a long journey.
 * Checkpoint failures are accumulated by the runner and reported after every
 * turn has run. Keep hard preconditions in `TurnSpec.assert` instead.
 */
export interface TurnCheckpoint {
	name: string;
	check: (turn: TurnResult, ctx: ScenarioContext, seed: SeedResult) => Promise<void> | void;
}

export type TurnEvidenceCheckCategory =
	| 'transport'
	| 'contract'
	| 'mutation'
	| 'effect'
	| 'collateral';

/**
 * An independently evaluated diagnostic subcheck. Unlike a checkpoint, a miss
 * never changes the official scenario verdict; it explains which layer failed
 * even when an earlier deterministic assertion already stopped the main gate.
 */
export interface TurnEvidenceCheck {
	name: string;
	category: TurnEvidenceCheckCategory;
	applies?: (ctx: ScenarioContext) => boolean;
	check: (turn: TurnResult, ctx: ScenarioContext, seed: SeedResult) => Promise<void> | void;
}

export interface TurnEvidenceCheckResult {
	name: string;
	category: TurnEvidenceCheckCategory;
	status: 'passed' | 'failed' | 'not_applicable';
	error: string | null;
}

/** One turn in a (possibly multi-turn) scenario. */
export interface TurnSpec {
	/** Human-readable phase name used in journey diagnostics. */
	label?: string;
	message: string;
	contextType: HarnessContextType;
	/** Resolve the project/entity id to scope this turn to, from the seed result. */
	entityIdFromSeed?: (seed: SeedResult) => string | undefined;
	/**
	 * Start this turn in a brand-new chat session, dropping the threaded session id and
	 * continuity context. Use for anything that must be proven to survive OUTSIDE the
	 * conversation — durable project state rather than recall from history. Without this,
	 * a "does it remember?" assertion can pass purely on conversation context.
	 */
	coldSession?: boolean;
	/** Deterministic assertions over the turn + DB + seed. Throw to fail. */
	assert: (turn: TurnResult, ctx: ScenarioContext, seed: SeedResult) => Promise<void> | void;
	/** Non-fatal quality checks accumulated until the scenario finishes. */
	checkpoints?: TurnCheckpoint[];
	/** Independent diagnostics retained in Phase 0 evidence, including after fail-fast gates. */
	evidenceChecks?: TurnEvidenceCheck[];
	/** Optional fuzzy-quality judge for this turn. */
	judge?: (
		turn: TurnResult,
		ctx: ScenarioContext,
		seed: SeedResult
	) => Promise<JudgeSpec & { transcript: string }>;
}

export interface Scenario {
	id: string;
	title: string;
	/**
	 * Grouping label. Doubles as the battery name selected by `AGENTIC_BATTERY`:
	 * `cedar-house` is the replay of the 2026-09-03 adversarial browser audit.
	 */
	category:
		| 'project'
		| 'document'
		| 'task'
		| 'organization'
		| 'calendar'
		| 'email'
		| 'creative'
		| 'cedar-house';
	/**
	 * Case number inside the battery, so a scorecard row lines up with the
	 * original audit's numbered table. Required for scenarios in a battery.
	 */
	batteryCase?: number;
	/** Override for long, multi-turn journeys. Defaults to the runner's 5 minutes. */
	timeoutMs?: number;
	/** Return true to skip (e.g. calendar without a connected test calendar). */
	skip?: () => boolean;
	/**
	 * Mutation tool names the worker must advertise (via /health
	 * agenticChat.mutationCapabilities) before this scenario is allowed to run
	 * in worker_realtime mode. Empty/unset scenarios skip the preflight.
	 */
	requiredMutationTools?: string[];
	/** Create fixtures. Omit for global/project_create scenarios. */
	seed?: (ctx: ScenarioContext) => Promise<SeedResult>;
	/**
	 * Extra cleanup beyond `seed.projectId`, which the runner always deletes.
	 * Needed by scenarios that seed several projects, or that may provoke the
	 * agent into creating an un-prefixed project the orphan sweep cannot find.
	 * Runs before the primary teardown; failures are logged, never fatal.
	 */
	teardown?: (ctx: ScenarioContext, seed: SeedResult) => Promise<void>;
	/** Turns run sequentially, reusing the session id across turns. */
	turns: TurnSpec[];
}
