-- Add summary field to chat_sessions table
-- This enables displaying chat session summaries on the history page alongside braindumps

-- Add summary column (nullable - existing sessions won't have summaries)
ALTER TABLE chat_sessions
ADD COLUMN IF NOT EXISTS summary TEXT;

-- Add index for efficient history queries (sessions with summaries or sufficient messages)
-- This supports the history page query: WHERE summary IS NOT NULL OR message_count >= 3
CREATE INDEX IF NOT EXISTS idx_chat_sessions_history_query
ON chat_sessions (user_id, created_at DESC)
WHERE status != 'archived';

-- Add partial index for sessions with summaries (faster lookup for classified sessions)
CREATE INDEX IF NOT EXISTS idx_chat_sessions_has_summary
ON chat_sessions (user_id, created_at DESC)
WHERE summary IS NOT NULL;

-- Documentation comment
COMMENT ON COLUMN chat_sessions.summary IS
'AI-generated summary of the conversation (max 500 chars). Generated by classify_chat_session worker job after session ends or reaches a message threshold.';
