-- supabase/migrations/20260502000002_agentic_chat_prepared_prompts.sql
-- Short-lived prepared prompt artifacts for agentic chat prewarm.

create table if not exists public.agentic_chat_prepared_prompts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  session_id uuid null references public.chat_sessions(id) on delete cascade,
  context_type text not null,
  entity_id uuid null,
  project_id uuid null,
  project_focus jsonb null,
  cache_key text not null,
  nonce_sha256 text not null,
  prompt_variant text not null default 'lite_seed_v1',
  context_cache_version integer not null,
  context_payload jsonb not null,
  conversation_summary text null,
  history_for_model jsonb not null default '[]'::jsonb,
  history_strategy text null,
  history_compressed boolean null,
  raw_history_count integer null,
  history_for_model_count integer null,
  prepared_surfaces jsonb not null,
  default_surface_profile text not null,
  context_payload_sha256 text not null,
  expires_at timestamptz not null,
  consumed_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint uq_agentic_chat_prepared_prompt_nonce unique (nonce_sha256),
  constraint chk_agentic_chat_prepared_prompt_expiry check (expires_at > created_at)
);

create index if not exists idx_agentic_chat_prepared_prompts_user_expires
  on public.agentic_chat_prepared_prompts(user_id, expires_at desc);

create index if not exists idx_agentic_chat_prepared_prompts_cache_key
  on public.agentic_chat_prepared_prompts(user_id, cache_key, expires_at desc);

create index if not exists idx_agentic_chat_prepared_prompts_cleanup
  on public.agentic_chat_prepared_prompts(expires_at, consumed_at);

drop trigger if exists trg_agentic_chat_prepared_prompts_updated on public.agentic_chat_prepared_prompts;
create trigger trg_agentic_chat_prepared_prompts_updated
before update on public.agentic_chat_prepared_prompts
for each row execute function public.set_updated_at();

alter table public.chat_turn_runs
  add column if not exists prepared_prompt_id uuid null references public.agentic_chat_prepared_prompts(id) on delete set null,
  add column if not exists prepared_prompt_hit boolean null,
  add column if not exists prepared_prompt_miss_reason text null,
  add column if not exists prepared_surface_profile text null;

create index if not exists idx_chat_turn_runs_prepared_prompt_id
  on public.chat_turn_runs(prepared_prompt_id)
  where prepared_prompt_id is not null;

alter table public.agentic_chat_prepared_prompts enable row level security;

drop policy if exists "prepared_prompts_user_insert" on public.agentic_chat_prepared_prompts;
create policy "prepared_prompts_user_insert"
  on public.agentic_chat_prepared_prompts
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "prepared_prompts_user_select" on public.agentic_chat_prepared_prompts;
create policy "prepared_prompts_user_select"
  on public.agentic_chat_prepared_prompts
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "prepared_prompts_user_update" on public.agentic_chat_prepared_prompts;
create policy "prepared_prompts_user_update"
  on public.agentic_chat_prepared_prompts
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "prepared_prompts_admin_select" on public.agentic_chat_prepared_prompts;
create policy "prepared_prompts_admin_select"
  on public.agentic_chat_prepared_prompts
  for select
  to authenticated
  using (is_admin());

drop policy if exists "prepared_prompts_service_role" on public.agentic_chat_prepared_prompts;
create policy "prepared_prompts_service_role"
  on public.agentic_chat_prepared_prompts
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

create or replace function public.cleanup_expired_agentic_chat_prepared_prompts()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_deleted integer;
begin
  delete from public.agentic_chat_prepared_prompts
  where expires_at < now() - interval '10 minutes'
     or consumed_at < now() - interval '10 minutes';

  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

revoke all on function public.cleanup_expired_agentic_chat_prepared_prompts() from public;
grant execute on function public.cleanup_expired_agentic_chat_prepared_prompts() to authenticated;
grant execute on function public.cleanup_expired_agentic_chat_prepared_prompts() to service_role;

comment on table public.agentic_chat_prepared_prompts is
'Short-lived server-owned prepared prompt artifacts generated by /api/agent/v2/prewarm.';
